import { defineArrayMember, defineField, defineType } from 'sanity';

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Réglages du site',
  type: 'document',
  fields: [
    defineField({ name: 'name', title: 'Nom', type: 'string', initialValue: 'Darryl Wassi' }),
    defineField({ name: 'tagline', title: 'Sous-titre (hero)', type: 'string', initialValue: 'The Digital Builder' }),
    defineField({ name: 'location', title: 'Localisation', type: 'string', initialValue: 'Yaoundé · Douala · Cameroun' }),
    defineField({ name: 'quote', title: 'Citation hero', type: 'string', initialValue: "I don't just imagine things — I build them." }),
    defineField({
      name: 'heroVideo',
      title: 'Vidéo de fond (hero)',
      type: 'file',
      options: { accept: 'video/*' },
      description: 'Boucle MP4 muette, idéalement < 6 Mo.',
    }),
    defineField({ name: 'heroPoster', title: 'Image de repli (hero)', type: 'image', options: { hotspot: true } }),
    defineField({
      name: 'manifesto',
      title: 'Texte manifeste',
      type: 'text',
      rows: 3,
      initialValue:
        'Darryl Wassi — développeur, créateur de contenu, entrepreneur et bâtisseur du numérique. Je transforme des idées en produits réels, depuis le Cameroun, pour l’Afrique et le monde.',
    }),
    defineField({
      name: 'socials',
      title: 'Réseaux sociaux',
      type: 'array',
      of: [
        defineArrayMember({
          name: 'social',
          type: 'object',
          fields: [
            { name: 'label', title: 'Nom', type: 'string' },
            { name: 'url', title: 'Lien', type: 'url' },
          ],
        }),
      ],
    }),
    defineField({ name: 'email', title: 'Email de contact', type: 'string', initialValue: 'darrylwassi@gmail.com' }),
    defineField({ name: 'whatsapp', title: 'Numéro WhatsApp', type: 'string', description: 'Format international sans + ni espaces, ex : 2376XXXXXXXX' }),
    defineField({ name: 'instagram', title: 'Instagram (lien ou @pseudo)', type: 'string' }),
    defineField({ name: 'substackUrl', title: 'URL Substack', type: 'url' }),
    defineField({ name: 'linkedinUrl', title: 'URL LinkedIn', type: 'url' }),
    defineField({
      name: 'sections',
      title: 'Titres & sous-titres des sections',
      type: 'object',
      description: 'Modifiez ici les titres et sous-titres affichés sur la page d’accueil.',
      options: { collapsible: true, collapsed: true },
      fields: [
        { name: 'aboutEyebrow', title: 'À propos — surtitre', type: 'string' },
        { name: 'venturesEyebrow', title: 'Ventures — surtitre', type: 'string' },
        { name: 'venturesTitle', title: 'Ventures — titre (ligne 1)', type: 'string' },
        { name: 'venturesTitleAccent', title: 'Ventures — titre (ligne 2, vert)', type: 'string' },
        { name: 'timelineEyebrow', title: 'Parcours — surtitre', type: 'string' },
        { name: 'timelineTitle', title: 'Parcours — titre (ligne 1)', type: 'string' },
        { name: 'timelineTitleAccent', title: 'Parcours — titre (ligne 2, vert)', type: 'string' },
        { name: 'spotlightEyebrow', title: 'Projet phare — surtitre', type: 'string' },
        { name: 'spotlightLogo', title: 'Projet phare — nom', type: 'string' },
        { name: 'spotlightTagline', title: 'Projet phare — accroche', type: 'text', rows: 2 },
        { name: 'spotlightCopy', title: 'Projet phare — texte', type: 'text', rows: 3 },
        { name: 'spotlightUrl', title: 'Projet phare — lien du bouton', type: 'url', description: 'Lien du bouton « Découvrir ».' },
        {
          name: 'spotlightImages',
          title: 'Projet phare — images de la galerie',
          type: 'array',
          description: 'Jusqu’à 4 visuels (captures du projet). La 1re image occupe la grande tuile à gauche.',
          of: [{ type: 'image', options: { hotspot: true } }],
          validation: (Rule) => Rule.max(4),
        },
        { name: 'newsEyebrow', title: 'Actualités — surtitre', type: 'string' },
        { name: 'newsTitle', title: 'Actualités — titre (ligne 1)', type: 'string' },
        { name: 'newsTitleAccent', title: 'Actualités — titre (ligne 2, vert)', type: 'string' },
        { name: 'newsletterTitle', title: 'Newsletter — titre', type: 'string' },
        { name: 'newsletterLead', title: 'Newsletter — sous-titre', type: 'text', rows: 2 },
      ],
    }),
  ],
  preview: { prepare: () => ({ title: 'Réglages du site' }) },
});
